In [3]:
import numpy as np

In [15]:
#print("Numpy imported")
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
#print(arr1)
arr2=np.array([1,2,3])
#print(arr2)
print(arr1+arr2)

Numpy imported
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [6]:
arr1=np.array([[1,2,3],[3,4,5]])
print("This is array 1 and it is mutable\n",arr1)
arr2=np.array([6,7,8])
print("This is array 2 and it is mutable\n",arr2)
print('Broadcasting')
print(arr1+arr2)

In [8]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1],[2]])
print(arr1+arr2)

[[2 3 4]
 [6 7 8]]


In [10]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([1])
print(arr1+arr2)

[[2 3 4]
 [5 6 7]]


In [12]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([1,2,3,4])
print(arr1+arr2)

ValueError: operands could not be broadcast together with shapes (6,) (4,) 

In [13]:
arr1=np.array([[1],[2],[3],[4],[5]])
arr2=np.array([1,2,3,4])
print(arr1+arr2)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]


In [17]:
arr=np.array([1,2,3])
print(arr*arr)
print(3*arr)

[1 4 9]
[3 6 9]
